// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/foo/foo.proto

package foo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateFooRequest) Reset() {
	*x = CreateFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooRequest) ProtoMessage() {}

func (x *CreateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooRequest.ProtoReflect.Descriptor instead.
func (*CreateFooRequest) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFooRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateFooReply) Reset() {
	*x = CreateFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooReply) ProtoMessage() {}

func (x *CreateFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooReply.ProtoReflect.Descriptor instead.
func (*CreateFooReply) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFooReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFooRequest) Reset() {
	*x = UpdateFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooRequest) ProtoMessage() {}

func (x *UpdateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooRequest.ProtoReflect.Descriptor instead.
func (*UpdateFooRequest) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{2}
}

type UpdateFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFooReply) Reset() {
	*x = UpdateFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooReply) ProtoMessage() {}

func (x *UpdateFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooReply.ProtoReflect.Descriptor instead.
func (*UpdateFooReply) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{3}
}

type DeleteFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFooRequest) Reset() {
	*x = DeleteFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooRequest) ProtoMessage() {}

func (x *DeleteFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooRequest.ProtoReflect.Descriptor instead.
func (*DeleteFooRequest) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{4}
}

type DeleteFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFooReply) Reset() {
	*x = DeleteFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooReply) ProtoMessage() {}

func (x *DeleteFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooReply.ProtoReflect.Descriptor instead.
func (*DeleteFooReply) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{5}
}

type GetFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFooRequest) Reset() {
	*x = GetFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooRequest) ProtoMessage() {}

func (x *GetFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooRequest.ProtoReflect.Descriptor instead.
func (*GetFooRequest) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{6}
}

type GetFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFooReply) Reset() {
	*x = GetFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooReply) ProtoMessage() {}

func (x *GetFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooReply.ProtoReflect.Descriptor instead.
func (*GetFooReply) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{7}
}

type ListFooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFooRequest) Reset() {
	*x = ListFooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFooRequest) ProtoMessage() {}

func (x *ListFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFooRequest.ProtoReflect.Descriptor instead.
func (*ListFooRequest) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{8}
}

type ListFooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFooReply) Reset() {
	*x = ListFooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foo_foo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFooReply) ProtoMessage() {}

func (x *ListFooReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foo_foo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFooReply.ProtoReflect.Descriptor instead.
func (*ListFooReply) Descriptor() ([]byte, []int) {
	return file_api_foo_foo_proto_rawDescGZIP(), []int{9}
}

var File_api_foo_foo_proto protoreflect.FileDescriptor

var file_api_foo_foo_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xd6, 0x02, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x5a, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x66, 0x6f, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x66, 0x6f,
	0x6f, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x3f, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6f, 0x6f, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6f, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x39, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x12, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1c, 0x0a,
	0x07, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x6f, 0x6f, 0x50, 0x01, 0x5a, 0x0f, 0x66, 0x6f, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6f, 0x3b, 0x66, 0x6f, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_foo_foo_proto_rawDescOnce sync.Once
	file_api_foo_foo_proto_rawDescData = file_api_foo_foo_proto_rawDesc
)

func file_api_foo_foo_proto_rawDescGZIP() []byte {
	file_api_foo_foo_proto_rawDescOnce.Do(func() {
		file_api_foo_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_foo_foo_proto_rawDescData)
	})
	return file_api_foo_foo_proto_rawDescData
}

var file_api_foo_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_foo_foo_proto_goTypes = []interface{}{
	(*CreateFooRequest)(nil), // 0: api.foo.CreateFooRequest
	(*CreateFooReply)(nil),   // 1: api.foo.CreateFooReply
	(*UpdateFooRequest)(nil), // 2: api.foo.UpdateFooRequest
	(*UpdateFooReply)(nil),   // 3: api.foo.UpdateFooReply
	(*DeleteFooRequest)(nil), // 4: api.foo.DeleteFooRequest
	(*DeleteFooReply)(nil),   // 5: api.foo.DeleteFooReply
	(*GetFooRequest)(nil),    // 6: api.foo.GetFooRequest
	(*GetFooReply)(nil),      // 7: api.foo.GetFooReply
	(*ListFooRequest)(nil),   // 8: api.foo.ListFooRequest
	(*ListFooReply)(nil),     // 9: api.foo.ListFooReply
}
var file_api_foo_foo_proto_depIdxs = []int32{
	0, // 0: api.foo.Foo.CreateFoo:input_type -> api.foo.CreateFooRequest
	2, // 1: api.foo.Foo.UpdateFoo:input_type -> api.foo.UpdateFooRequest
	4, // 2: api.foo.Foo.DeleteFoo:input_type -> api.foo.DeleteFooRequest
	6, // 3: api.foo.Foo.GetFoo:input_type -> api.foo.GetFooRequest
	8, // 4: api.foo.Foo.ListFoo:input_type -> api.foo.ListFooRequest
	1, // 5: api.foo.Foo.CreateFoo:output_type -> api.foo.CreateFooReply
	3, // 6: api.foo.Foo.UpdateFoo:output_type -> api.foo.UpdateFooReply
	5, // 7: api.foo.Foo.DeleteFoo:output_type -> api.foo.DeleteFooReply
	7, // 8: api.foo.Foo.GetFoo:output_type -> api.foo.GetFooReply
	9, // 9: api.foo.Foo.ListFoo:output_type -> api.foo.ListFooReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_foo_foo_proto_init() }
func file_api_foo_foo_proto_init() {
	if File_api_foo_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_foo_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foo_foo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_foo_foo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_foo_foo_proto_goTypes,
		DependencyIndexes: file_api_foo_foo_proto_depIdxs,
		MessageInfos:      file_api_foo_foo_proto_msgTypes,
	}.Build()
	File_api_foo_foo_proto = out.File
	file_api_foo_foo_proto_rawDesc = nil
	file_api_foo_foo_proto_goTypes = nil
	file_api_foo_foo_proto_depIdxs = nil
}
